dist: xenial
language: python

python:
  - "3.6"

install:
  - sudo apt install build-essential
  - export INSTALL_ON_LINUX=1; pip install xlwings
  - sudo apt-get install python3-dev python3-pip python3-venv python3-wheel -y
  - pip install wheel
  - pip install -r requirements.txt
  - sudo apt-get install gcc libpq-dev -y
  - sudo apt-get install python-dev  python-pip -y

script: python -m unittest discover test
