log:
  filename: 'helpbot.log'
token: ''
data: 'helpbot/data/help_title_v2.csv'
vectorizer: 'helpbot/bin/vectorizer.joblib'
section_1_encoder: 'helpbot/bin/section_1_encoder.joblib'
section_2_encoder: 'helpbot/bin/section_2_encoder.joblib'
section_3_encoder: 'helpbot/bin/section_3_encoder.joblib'
section_1_ovr: 'helpbot/bin/section_1_ovr.joblib'
section_2_ovr: 'helpbot/bin/section_2_ovr.joblib'
section_3_ovr: 'helpbot/bin/section_3_ovr.joblib'